#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : idna
Version  : 2.8
Release  : 46
URL      : https://files.pythonhosted.org/packages/ad/13/eb56951b6f7950cadb579ca166e448ba77f9d24efc03edd7e55fa57d04b7/idna-2.8.tar.gz
Source0  : https://files.pythonhosted.org/packages/ad/13/eb56951b6f7950cadb579ca166e448ba77f9d24efc03edd7e55fa57d04b7/idna-2.8.tar.gz
Summary  : Internationalized Domain Names in Applications (IDNA)
Group    : Development/Tools
License  : ICU
Requires: idna-license = %{version}-%{release}
Requires: idna-python = %{version}-%{release}
Requires: idna-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils23
BuildRequires : buildreq-distutils3
BuildRequires : setuptools-legacypython

%description
=====================================================
        
        Support for the Internationalised Domain Names in Applications

%package legacypython
Summary: legacypython components for the idna package.
Group: Default
Requires: python-core

%description legacypython
legacypython components for the idna package.


%package license
Summary: license components for the idna package.
Group: Default

%description license
license components for the idna package.


%package python
Summary: python components for the idna package.
Group: Default
Requires: idna-python3 = %{version}-%{release}

%description python
python components for the idna package.


%package python3
Summary: python3 components for the idna package.
Group: Default
Requires: python3-core

%description python3
python3 components for the idna package.


%prep
%setup -q -n idna-2.8

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1543988303
python2 setup.py build -b py2
python3 setup.py build -b py3

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
PYTHONPATH=%{buildroot}/usr/lib/python3.7/site-packages python3 setup.py test
%install
export SOURCE_DATE_EPOCH=1543988303
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/idna
cp LICENSE.rst %{buildroot}/usr/share/package-licenses/idna/LICENSE.rst
python2 -tt setup.py build -b py2 install --root=%{buildroot} --force
python3 -tt setup.py build -b py3 install --root=%{buildroot} --force
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files legacypython
%defattr(-,root,root,-)
/usr/lib/python2*/*

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/idna/LICENSE.rst

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
